
alias conf="vim $HOME/.config/fish/config.fish"
alias confvim="vim $HOME/.vimrc"
alias confalias="vim $HOME/.config/fish/aliases.fish"
alias al="vim $HOME/.config/fish/aliases.fish"
alias reload="source $HOME/.config/fish/config.fish"
alias ncdu="ncdu --color dark"

alias gc="git checkout"
alias gs="git status"
alias ga="git add"
alias gaa="git add ."
alias gp="git push"
alias gpl="git pull"
alias gcm="git commit -m"
alias gco="git checkout"
alias gcl="git clone"
alias gbr="git branch"
alias gdf="git diff"
alias glog="git log"
alias greset="git reset"
alias grh="git reset --hard"
alias gmerge="git merge"
alias gfetch="git fetch"
alias gpr="git pull --rebase"
alias grc="git rebase --continue"
alias gra="git rebase --abort"
alias gr="git rebase"
